In [27]:
import pandas as pd 

import pymysql #this will work as adapter
from sqlalchemy import create_engine

#psql

In [28]:
print(pd.__version__)

3.0.2

In [29]:
df=pd.read_csv('Walmart.csv', encoding_errors='ignore')
df.shape

(10051, 11)

In [30]:

df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [32]:
df.duplicated().sum()

np.int64(51)

In [33]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [34]:
df.dropna(inplace=True)

# verify
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [35]:
df['unit_price'] = df['unit_price'].str.replace('$', '').astype(float)

df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [36]:
df['total'] = df['unit_price'] * df['quantity']
df.columns = df.columns.str.lower()

In [37]:
df.shape

(9969, 12)

In [38]:
df.to_csv('walmart_clean_data.csv', index=False)

In [39]:
engine_mysql = create_engine("mysql+pymysql://root@localhost:3306/walmart_db")

try:
    engine_mysql
    print("Connection Successed to mysql")
except:
    print("Unable to connect")

Connection Successed to mysql

In [40]:
df.to_sql(name='walmart', con=engine_mysql, if_exists='append', index=False)

9969